config/routes.rb
Rails.application.routes.draw do

   root 'users#index'

    resources :users

    post '/signin', to:'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    post '/follow/:id', to: 'users#follow', as: 'follow'
    get '/profile', to: 'users#profile'
    post '/unfollow/:id', to: 'users#unfollow', as: 'unfollow'

    resources :users do 
      member do 
        get :following, :followers
      end 
    end

    resources :posts do
      resources :comments
    end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user, foreign_key: "userid"
	belongs_to :post, foreign_key: "postid"
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user, foreign_key: "userid"
	has_many :comments,foreign_key: "postid"
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments, foreign_key: "userid", dependent: :destroy
	has_many :posts, foreign_key: "userid", dependent: :destroy

	validates :email, presence: true
	
	has_many :active_relationships,  class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:  :destroy
	  has_many :passive_relationships, class_name:  "Relationship",
	                                  foreign_key: "followed_id",
	                                  dependent:  :destroy
	  has_many :following, through: :active_relationships,  source: :followed
	  has_many :followers, through: :passive_relationships, source: :follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def current_user
  	session[:user_id] ? User.find(session[:user_id]) : nil
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def edit
  end

  def new
   @comment=Comment.new
  end

  def show
  end


  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.create(comment_params)
    redirect_to post, notice: "New comment created."
  end

  def update
  
 
  end

  def destroy
  

  end



private
 def comment_params
    params.require(:comment).permit(:text_comment).merge(userid: current_user.id)
 
  end








end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: [:edit, :update, :show, :destroy]
  def index
    @user=current_user
    @users=User.all
    
  end

  def edit
  end

  def new
  	 @post=Post.new
  end

  def show
    @comment = Comment.new
  end

  def create
   @post = Post.create(post_params)
   redirect_to user_path(current_user), notice: "New post created."
  end

  def update
  @post.update(post_params)
  redirect_to @post,notice: "Post Updated."
  end

  def destroy
  @post.destroy
  redirect_to user_path(@post.user), notice: "Post deleted."
  end

 private

  def post_params
    params.require(:post).permit(:title, :body).merge(userid: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
	def create
		
			@user=User.find_by(email: params[:email])
			
			if @user and @user.password == params[:password]
				flash[:notice]="Successfully signed in!"
				session[:user_id]=@user.id
				redirect_to profile_path
			 else
			    flash[:alert]="User does not exist. Please sign up."
			    redirect_to root_path
		    end
	  
		
	end
	def destroy
		session[:user_id]=nil
		flash[:notice]="Logged out..."
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show, :destroy]
  
  def profile
    if current_user 
      @comment = Comment.new
      @user = current_user
      @users= User.all
      render :show
      else
        redirect_to root_path
      end
  end

  def index
   
  end
 
  def create
  	
    @user=User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
  	   redirect_to @user,notice: "New user created."
     else
      render 'new'
    end
  end
 
  def edit
    @custom_text="Edit Account"
  end

  def new
    @user=User.new
    @custom_text="Sign Up"
  end

  def show
    @users= User.all
    @comment = Comment.new
  end
 
  def update
    @user=User.update(@user.id, user_params)
    redirect_to @user,notice: "User Updated."
  end

   def destroy
    @user.destroy
    if session[:user_id] == @user.id
      session[:user_id]=nil
    end
    
    redirect_to @user, notice: "Account canceled."
  end

  def follow
    @user = User.find(params[:id])
    @rel = Relationship.create(follower_id: current_user.id, followed_id: @user.id)
    redirect_to profile_path
  end

  def unfollow
    @user = User.find(params[:id])
    @rel = Relationship.where(follower_id: current_user.id, followed_id: @user.id)
    @rel.first.destroy
    redirect_to profile_path
  end





  

  private
  def set_user
  	@user = User.find(params[:id])
  end
  def user_params
  	params.require(:user).permit(:email, :name, :bio, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
  	session[:user_id] ? User.find(session[:user_id]) : nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	

	def show_follow_link
		if !current_user
			 link_to 'follow user', follow_path(@user), method: :post 
		end
	end


end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  
	<%= f.text_area :text_comment %><br />
	<%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogSomyaJim</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:400,300italic,400italic' rel='stylesheet' type='text/css'>
</head>
<body>
	<div id="container">
<!-- <h1><%= current_user ? current_user.name : "no user logged in" %></h1> -->
	<%= flash[:notice] if flash[:notice] %>
	<%= flash[:alert] if flash[:alert] %>
	<%= yield %>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
	

		<%= form_for @post do |f| %>
		  
		
		  <%= f.text_field :title, :placeholder => 'title'%>
		  
		  
		  <div class="textarea"><%= f.text_area :body, :placeholder => 'body'%></div>


		  
		 <%= f.submit %>
		<% end %>

app/views/posts/edit.html.erb
<div class="postShowContainer">
	<ul>
		<li><%= link_to 'cancel', posts_path %></li>
	</ul>

	<div class ="postForm">
		<%= render 'form' %>
	</div>

</div>

app/views/posts/index.html.erb
<div>

	<div id="postsContainer">
		
		<h2>Posts</h2>
			<ul>
				<% @user.following.each do |user|%>
					<% user.posts.each do |post|%>
							<%=post.title%> by<%=@user.name%>
							<%=post.body%>
						<%end%>
				<%end%>
			</ul>
	</div>

</div>

app/views/posts/new.html.erb
<div class="postContainer">
<h1>New Post</h1>
<div class="postHeader">
	<nav>
		<ul id="signupMenu">	
			<%= link_to 'Cancel', user_path(current_user), method: :get %>
		</ul>
	</nav>

<div class ="postForm"><%= render 'form' %></div>
<br/>
</div>
</div>

app/views/posts/show.html.erb
<div class="postShowContainer">
	
	<nav>
		<ul id="showPostMenu">	
			<li><%= link_to 'Edit post', edit_post_path %> </li>
			<li><%= link_to 'Delete post', post_path, method: :delete%></li>
		</ul>
	</nav>
	
	<div class ="postForm">
		
		<h1><%= @post.title %></h1>
		<p>created at: <%= @post.created_at %></p>

		<p class="post-body"><%= @post.body %></p>			
		<a class="show-comment">comment</a>
		<div class="comment-box"><%= render 'comments/form' %></div>
			

			<% @post.comments.each do |comment| %>
				<p><%= comment.text_comment%></p>
			<% end %>
	


	</div>


</div>



				
				

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_form.html.erb
<% if @user.errors.full_messages.any? %>
	 <ul>
		 <% @user.errors.full_messages.each do |message| %>
		 	<li><%= message%></li> 
	 	 <% end %>
	</ul>
<%end%>
	<div id="signup_pic">
		<div class="signup"><%= form_for @user do |f| %>
		  
		  <%= f.text_field :name, required: true, :placeholder => 'Name' %><br />
		  
		 
		  <%= f.email_field :email , :placeholder => 'email'%><br />
		  
		  
		  <%= f.text_area :bio, required: true, :placeholder => 'bio' %><br />

		  
		  <%= f.text_area :username, required: true, :placeholder => 'username' %><br />
		  
		 
		  <%= f.password_field :password, required: true , :placeholder => 'password'%><br />
		  
		  <%= f.submit @custom_text %>
		  
		  <% end %>
		</div>
	</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
            html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<div id="editContainer">



	<nav>
		<ul id="profileMenu">	
			<%= link_to 'Delete Account', user_path(current_user), method: :delete %>
			<%= link_to 'Cancel', user_path(current_user) %>
		</ul>
	</nav>

<%= render 'form' %>

<h1>/h1>

</div>



			

app/views/users/index.html.erb
<div id="indexContainer">
	
	<h1 class="musicBlog">Music Blog</h1>

	<div class="signin"><%if current_user%>
	    <p> Hello <%=current_user.name%> | 
	      <%=link_to 'sign out', logout_path, method: :delete%></p>
	      <%else%>
	 
	 <%= form_tag(signin_path, method: :post) do %>

	    <%= label_tag :email  %>
	    <%= email_field_tag :email %>
	    <%= label_tag :password %>
	    <%= password_field_tag :password %>
	    <%= submit_tag "login" %>
	  <%end%>

	 

	 <%= form_tag(new_user_path, method: :get) do %>
	    <%= submit_tag "New User? Sign up.." %>
	    <%end%>
	  <%end%>

	</div>
</div>

app/views/users/new.html.erb
<div id="signupContainer">
	
	<nav>
		<ul id="signupMenu">	
			<%= link_to 'Cancel', @user%>
		</ul>
	</nav>

	<%= render 'form' %>
	<br/>
	
</div>

app/views/users/show.html.erb
<div class="profile_container">
	<header id="profileHeader">
		<%# render 'follow'  %>
	
  
			<nav>
				<ul id="profileMenu">	
					<li><%= link_to 'Home', posts_path, method: :get %></li>
					<li><%= link_to 'Create Post', new_post_path, method: :get %></li>
					<li><%= link_to 'Edit Profile', edit_user_path(@user) %></li>
					<li><%= link_to 'Log out', logout_path , method: :delete %> </li>
				</ul>
			</nav>

		<div class="profileInfo">
			
			

			<h1 class="header"> <h3 class="showName"> <%= "  #{ @user.name.capitalize} "%></h3></h1>
			
			

			<h3 class="showBio"><%= @user.bio %></h3>
				<%if current_user != @user%>
					<%= link_to ' | follow ', follow_path(@user), method: :post %>
					<%end%>
			<!-- <h4 class="postCount"> Posts:</h4> -->
			<p class="showBio"><%= pluralize(@user.posts.size, 'post') %></p>
			<p class="showBio"><%= @user.following.size%> following</p>
			<p class="showBio"><%= pluralize(@user.followers.size, 'followers') %></p>
		</div>
	

		
	</header>
	
	<aside id="UserFollowingFollowers">
				
				<div id="usersList">
					
					<h2>Suggested people to follow</h2>
						<ul>
							<% @users.each do |user|%>
								<% if user.following%>
										<li> <%=link_to  user.name, user_path(user) %> </li>
									<%end%>
							<%end%>
						</ul>
				</div>

				<div id="followersList">
					<h1 id="followingList">I am Following<h1>
					<ul>
						<% @users.each do |user|%>
							<% user.following.each do |u| %>
								<li> <%=link_to  u.name, user_path(u.id)  %> |<%= link_to 'unfollow', unfollow_path(u.id), method: :post %></li>
								<%end%>
						<%end%>
					</ul>
				</div>

				<div id="followedList">
					<h1 id="following_me">Followers<h1>
					<ul>
						
						<% @users.each do |user|%>
							<% user.followers.each do |u| %>
									<% if u.id != @user.id%>
										<li> <%=link_to  u.name, user_path(u.id) %>  </li>
									<%end%>
								<%end%>
						<%end%>
					</ul>
				</div>
			</aside>			
	


	
		<ul>
		  	<% @user.posts.each do |post| %>
		  		<h1 id="PostTitle"><%=  link_to(  post.title, post_path(post.id)    )%></h1><h2>by <%=post.user.name%><%=post.created_at%> <%=post.updated_at%>  </h2>
		  
			<% end %>
		</ul>

	


	

	


	

	


</div>